name: Publish package to the Maven Central Repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion }}"
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      #- name: Import GPG Key
      #  id: import_gpg
      #  uses: crazy-max/ghaction-import-gpg@v6
      #  with:
      #    gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      #    git_user_signingkey: true
      #    git_commit_gpgsign: true
      - name: echo
        run: cat ~/.m2/settings.xml
      - name: Publish package
        id: publish_package
        run: MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=trace mvn -B -U -P ci-cd -DskipTests=true -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Denv.MAVEN_USERNAME=${{ secrets.OSS_SONATYPE_USERNAME }} -Denv.MAVEN_PASSWORD=${{ secrets.OSS_SONATYPE_PASSWORD }} deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
